
import { GoogleGenAI } from "@google/genai";
import { AspectRatio } from "../types";

export const editImage = async (
  base64Data: string,
  mimeType: string,
  prompt: string,
  aspectRatio: AspectRatio = AspectRatio.PORTRAIT
): Promise<{ imageUrl: string; mimeType: string }> => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API Key is missing. Please check your environment variables.");
  }

  const ai = new GoogleGenAI({ apiKey });
  
  const imagePart = {
    inlineData: {
      data: base64Data,
      mimeType: mimeType,
    },
  };

  const textPart = {
    text: prompt,
  };

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: { parts: [imagePart, textPart] },
    config: {
      imageConfig: {
        aspectRatio: aspectRatio as any,
      },
    },
  });

  const candidates = response.candidates || [];
  if (candidates.length === 0) {
    throw new Error("No image was generated by the model.");
  }

  const parts = candidates[0].content.parts;
  const imagePartFound = parts.find((p) => p.inlineData);

  if (!imagePartFound || !imagePartFound.inlineData) {
    throw new Error("API returned success but no image data was found in the response.");
  }

  return {
    imageUrl: `data:${imagePartFound.inlineData.mimeType};base64,${imagePartFound.inlineData.data}`,
    mimeType: imagePartFound.inlineData.mimeType,
  };
};
